const GET_RECIPE_ALL = 'GET_RECIPE_ALL';
const GET_RECIPE_NAME = 'GET_RECIPE_NAME';
const GET_DIETS_ALL = 'GET_DIETS_ALL';
const FILTER_BY_ORDER = 'Filter_By_ORDER';
const FILTER_BY_CREATE = 'FILTER_BY_CREATE';
const FILTER_BY_SCORE = 'FILTER_BY_SCORE';
const FILTER_BY_DIETS = 'FILTER_BY_DIETS';

module.exports = {
    GET_RECIPE_ALL,
    GET_RECIPE_NAME,
    GET_DIETS_ALL,
    FILTER_BY_ORDER,
    FILTER_BY_CREATE,
    FILTER_BY_SCORE,
    FILTER_BY_DIETS,
}