const GET_RECIPE_ALL = 'GET_RECIPE_ALL';
const GET_RECIPE_NAME = 'GET_RECIPE_NAME';
const FILTER_BY_ORDER = 'Filter_By_ORDER';
const FILTER_BY_CREATE = 'FILTER_BY_CREATE';

module.exports = {
    GET_RECIPE_ALL,
    GET_RECIPE_NAME,
    FILTER_BY_ORDER,
    FILTER_BY_CREATE,
}